[project]
name = "bigdata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy<2.0.0",
    "pandas>=2.2.3",
    "setuptools>=76.0.0",
    "sweetviz>=2.3.1",
]
